semester_tag="2025L"
class_usos_webpage="https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=103A-INSZI-MSP-AMHE"
class_name_full="Algorytmy Metaheurystyczne"
class_name_short="amhe"
task_assignment_date="TBA"
init_doc_date="TBA"
partial_presentation_date="TBA"
end_doc_date="TBA"
feasible_delay_start_date="TBA"
feasible_delay_end_date="TBA"
infeasible_delay_date="TBA"
task_publish_date="TBA"
doc_template_url="TODO"
doc_template_name="TODO"
