semester_tag="2025L"
class_usos_webpage="https://usosweb.usos.pw.edu.pl/kontroler.php?_action=katalog2/przedmioty/pokazPrzedmiot&prz_kod=1120-INMSI-MSP-0125"
class_name_full="Wstęp do algorytmów ewolucyjnych"
class_name_short="wae"
task_assignment_date="31.03.2025"
init_doc_date="14.04.2025"
partial_presentation_date="26.05.2025"
end_doc_date="16.06.2025"
feasible_delay_start_date="17.06.2025"
feasible_delay_end_date="23.06.2025"
infeasible_delay_date="23.06.2025"
task_publish_date="22.03.2025"
