semester_tag="2025L"
class_name_full="Wstęp do sztucznej inteligencji"
lab_start_time="12:15"
lab_end_time="14:00"
lab_room="011"
lab_1_start_date="2025-03-04"
lab_2_start_date="2025-03-18"
lab_3_start_date="2025-04-01"
lab_4_start_date="2025-04-15"
lab_5_start_date="2025-05-06"
lab_6_start_date="2025-05-20"
lab_7_start_date="2025-06-03"
